name: TestingGrounds
version: '1.0-SNAPSHOT'
main: me.Cyrendex.testingGrounds.TestingGrounds
api-version: '1.21'
authors: [ Cyrendex ]
description: Experimenting with plugin development
commands:
    god:
        description: Become invincible
        usage: /<command>
        aliases:
          - godmode
          - invincible
          - invulnerable
    feed:
        description: Feed the player mmm yum
        usage: /<command> [player]


